/* Generated by src/build_web_data.py — do not edit by hand */
window.AMAZONIQ_DATA = {
  "generated_at": "2026-08-19T00:33:22Z",
  "disclaimer": "Illustrative planning on Google Trends search-interest proxy. Not Amazon warehouse units. Public data only.",
  "companion_note": "Interactive companion to the Power BI / DAX semantic model (dashboard/AmazonIQ.pbip).",
  "categories": [
    {
      "category_id": "electronics",
      "category_name": "Electronics",
      "keyword": "headphones",
      "catalog_product_count": 49452,
      "baseline_mape_pct": 30.22,
      "catalog_share_of_max": 0.35
    },
    {
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "keyword": "air fryer",
      "catalog_product_count": 17717,
      "baseline_mape_pct": 19.58,
      "catalog_share_of_max": 0.1254
    },
    {
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "keyword": "running shoes",
      "catalog_product_count": 141291,
      "baseline_mape_pct": 40.04,
      "catalog_share_of_max": 1.0
    },
    {
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "keyword": "vitamins",
      "catalog_product_count": 31423,
      "baseline_mape_pct": 14.51,
      "catalog_share_of_max": 0.2224
    },
    {
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "keyword": "lawn mower",
      "catalog_product_count": 5345,
      "baseline_mape_pct": 18.89,
      "catalog_share_of_max": 0.0378
    },
    {
      "category_id": "toys",
      "category_name": "Toys & Games",
      "keyword": "toys",
      "catalog_product_count": 83133,
      "baseline_mape_pct": 16.66,
      "catalog_share_of_max": 0.5884
    }
  ],
  "forecast_metrics": [
    {
      "category_id": "electronics",
      "category_name": "Electronics",
      "keyword": "headphones",
      "mape_pct": 30.22,
      "weak_accuracy_flag": true,
      "weak_accuracy_reason": "MAPE 30.2% exceeds 25% threshold; April 2026 spike (DQ-011) \u2014 atypical vs holiday seasonality"
    },
    {
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "keyword": "air fryer",
      "mape_pct": 19.58,
      "weak_accuracy_flag": true,
      "weak_accuracy_reason": "moderate MAPE 19.6%"
    },
    {
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "keyword": "running shoes",
      "mape_pct": 40.04,
      "weak_accuracy_flag": true,
      "weak_accuracy_reason": "MAPE 40.0% exceeds 25% threshold"
    },
    {
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "keyword": "vitamins",
      "mape_pct": 14.51,
      "weak_accuracy_flag": false,
      "weak_accuracy_reason": "July 2026 spike (DQ-013) \u2014 peak outside expected January window; low volatility (std < 8) \u2014 MAPE sensitive to small absolute errors"
    },
    {
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "keyword": "lawn mower",
      "mape_pct": 18.89,
      "weak_accuracy_flag": true,
      "weak_accuracy_reason": "Strong spring seasonality; keyword 'lawn mower' is narrow vs Census garden analog"
    },
    {
      "category_id": "toys",
      "category_name": "Toys & Games",
      "keyword": "toys",
      "mape_pct": 16.66,
      "weak_accuracy_flag": true,
      "weak_accuracy_reason": "moderate MAPE 16.7%"
    }
  ],
  "inventory_planning": [
    {
      "category_id": "electronics",
      "category_name": "Electronics",
      "keyword": "headphones",
      "safety_stock": 70.78,
      "reorder_point": 132.78,
      "mape_pct_baseline": 30.22,
      "uncertainty_tier": "high",
      "high_uncertainty_flag": true,
      "service_level_pct": 95.0,
      "lead_time_weeks": 2
    },
    {
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "keyword": "air fryer",
      "safety_stock": 33.49,
      "reorder_point": 142.49,
      "mape_pct_baseline": 19.58,
      "uncertainty_tier": "elevated",
      "high_uncertainty_flag": false,
      "service_level_pct": 95.0,
      "lead_time_weeks": 2
    },
    {
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "keyword": "running shoes",
      "safety_stock": 77.39,
      "reorder_point": 131.39,
      "mape_pct_baseline": 40.04,
      "uncertainty_tier": "high",
      "high_uncertainty_flag": true,
      "service_level_pct": 95.0,
      "lead_time_weeks": 2
    },
    {
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "keyword": "vitamins",
      "safety_stock": 26.34,
      "reorder_point": 155.34,
      "mape_pct_baseline": 14.51,
      "uncertainty_tier": "standard",
      "high_uncertainty_flag": false,
      "service_level_pct": 95.0,
      "lead_time_weeks": 2
    },
    {
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "keyword": "lawn mower",
      "safety_stock": 32.24,
      "reorder_point": 135.24,
      "mape_pct_baseline": 18.89,
      "uncertainty_tier": "elevated",
      "high_uncertainty_flag": false,
      "service_level_pct": 95.0,
      "lead_time_weeks": 2
    },
    {
      "category_id": "toys",
      "category_name": "Toys & Games",
      "keyword": "toys",
      "safety_stock": 20.86,
      "reorder_point": 112.86,
      "mape_pct_baseline": 16.66,
      "uncertainty_tier": "elevated",
      "high_uncertainty_flag": false,
      "service_level_pct": 95.0,
      "lead_time_weeks": 2
    }
  ],
  "forecast_backtest": {
    "electronics": [
      {
        "ds": "2026-02-15",
        "actual": 30.0,
        "predicted": 28.983625787345893
      },
      {
        "ds": "2026-02-22",
        "actual": 29.0,
        "predicted": 28.368474465749003
      },
      {
        "ds": "2026-03-01",
        "actual": 29.0,
        "predicted": 28.768051908543182
      },
      {
        "ds": "2026-03-08",
        "actual": 29.0,
        "predicted": 29.559591059378764
      },
      {
        "ds": "2026-03-15",
        "actual": 32.0,
        "predicted": 29.484605151186095
      },
      {
        "ds": "2026-03-22",
        "actual": 57.0,
        "predicted": 28.277622291593598
      },
      {
        "ds": "2026-03-29",
        "actual": 80.0,
        "predicted": 27.010324897566793
      },
      {
        "ds": "2026-04-05",
        "actual": 88.0,
        "predicted": 26.774070779110602
      },
      {
        "ds": "2026-04-12",
        "actual": 100.0,
        "predicted": 27.407136689481476
      },
      {
        "ds": "2026-04-19",
        "actual": 83.0,
        "predicted": 27.844637743752948
      },
      {
        "ds": "2026-04-26",
        "actual": 67.0,
        "predicted": 27.581276309804075
      },
      {
        "ds": "2026-05-03",
        "actual": 71.0,
        "predicted": 27.358925698589868
      },
      {
        "ds": "2026-05-10",
        "actual": 68.0,
        "predicted": 28.21008992169126
      },
      {
        "ds": "2026-05-17",
        "actual": 48.0,
        "predicted": 30.062418457990347
      },
      {
        "ds": "2026-05-24",
        "actual": 40.0,
        "predicted": 31.644272198794393
      },
      {
        "ds": "2026-05-31",
        "actual": 39.0,
        "predicted": 31.82498149260361
      },
      {
        "ds": "2026-06-07",
        "actual": 45.0,
        "predicted": 30.81209235349427
      },
      {
        "ds": "2026-06-14",
        "actual": 44.0,
        "predicted": 29.866602710918475
      },
      {
        "ds": "2026-06-21",
        "actual": 52.0,
        "predicted": 29.970540152465503
      },
      {
        "ds": "2026-06-28",
        "actual": 33.0,
        "predicted": 30.984416029440286
      },
      {
        "ds": "2026-07-05",
        "actual": 31.0,
        "predicted": 32.06730012950042
      },
      {
        "ds": "2026-07-12",
        "actual": 28.0,
        "predicted": 32.63533518506931
      },
      {
        "ds": "2026-07-19",
        "actual": 29.0,
        "predicted": 32.73948342137072
      },
      {
        "ds": "2026-07-26",
        "actual": 28.0,
        "predicted": 32.687370237491535
      },
      {
        "ds": "2026-08-02",
        "actual": 29.0,
        "predicted": 32.614705904359376
      },
      {
        "ds": "2026-08-09",
        "actual": 38.0,
        "predicted": 32.48980073098693
      }
    ],
    "home_kitchen": [
      {
        "ds": "2026-02-15",
        "actual": 52.0,
        "predicted": 54.0506596862326
      },
      {
        "ds": "2026-02-22",
        "actual": 48.0,
        "predicted": 50.74172991293746
      },
      {
        "ds": "2026-03-01",
        "actual": 48.0,
        "predicted": 48.0675691147836
      },
      {
        "ds": "2026-03-08",
        "actual": 52.0,
        "predicted": 47.42245403446818
      },
      {
        "ds": "2026-03-15",
        "actual": 50.0,
        "predicted": 47.688772239803846
      },
      {
        "ds": "2026-03-22",
        "actual": 58.0,
        "predicted": 47.04784321905408
      },
      {
        "ds": "2026-03-29",
        "actual": 70.0,
        "predicted": 45.28968091927749
      },
      {
        "ds": "2026-04-05",
        "actual": 78.0,
        "predicted": 43.78435403087769
      },
      {
        "ds": "2026-04-12",
        "actual": 83.0,
        "predicted": 43.48277997634973
      },
      {
        "ds": "2026-04-19",
        "actual": 74.0,
        "predicted": 43.703307776149764
      },
      {
        "ds": "2026-04-26",
        "actual": 64.0,
        "predicted": 43.189723347839724
      },
      {
        "ds": "2026-05-03",
        "actual": 72.0,
        "predicted": 41.90165570013712
      },
      {
        "ds": "2026-05-10",
        "actual": 67.0,
        "predicted": 41.14661127010279
      },
      {
        "ds": "2026-05-17",
        "actual": 56.0,
        "predicted": 41.91178814156809
      },
      {
        "ds": "2026-05-24",
        "actual": 56.0,
        "predicted": 43.57826096763338
      },
      {
        "ds": "2026-05-31",
        "actual": 51.0,
        "predicted": 44.655583627929616
      },
      {
        "ds": "2026-06-07",
        "actual": 57.0,
        "predicted": 44.58298650547983
      },
      {
        "ds": "2026-06-14",
        "actual": 55.0,
        "predicted": 44.3484642688698
      },
      {
        "ds": "2026-06-21",
        "actual": 60.0,
        "predicted": 45.22198162482471
      },
      {
        "ds": "2026-06-28",
        "actual": 53.0,
        "predicted": 47.21267005179009
      },
      {
        "ds": "2026-07-05",
        "actual": 49.0,
        "predicted": 49.06524724681986
      },
      {
        "ds": "2026-07-12",
        "actual": 49.0,
        "predicted": 49.64001915588129
      },
      {
        "ds": "2026-07-19",
        "actual": 50.0,
        "predicted": 48.96252396121367
      },
      {
        "ds": "2026-07-26",
        "actual": 55.0,
        "predicted": 47.88855905628134
      },
      {
        "ds": "2026-08-02",
        "actual": 53.0,
        "predicted": 47.0900686019118
      },
      {
        "ds": "2026-08-09",
        "actual": 60.0,
        "predicted": 46.62804988860081
      }
    ],
    "clothing": [
      {
        "ds": "2026-02-15",
        "actual": 27.0,
        "predicted": 21.019879259091052
      },
      {
        "ds": "2026-02-22",
        "actual": 26.0,
        "predicted": 21.22208674210962
      },
      {
        "ds": "2026-03-01",
        "actual": 24.0,
        "predicted": 21.784578337429675
      },
      {
        "ds": "2026-03-08",
        "actual": 23.0,
        "predicted": 22.755819888037475
      },
      {
        "ds": "2026-03-15",
        "actual": 25.0,
        "predicted": 23.28512749210739
      },
      {
        "ds": "2026-03-22",
        "actual": 37.0,
        "predicted": 22.772496339455778
      },
      {
        "ds": "2026-03-29",
        "actual": 71.0,
        "predicted": 21.74134189267823
      },
      {
        "ds": "2026-04-05",
        "actual": 93.0,
        "predicted": 21.295137570160158
      },
      {
        "ds": "2026-04-12",
        "actual": 100.0,
        "predicted": 21.82915554279711
      },
      {
        "ds": "2026-04-19",
        "actual": 74.0,
        "predicted": 22.59953580822862
      },
      {
        "ds": "2026-04-26",
        "actual": 61.0,
        "predicted": 22.66029765387625
      },
      {
        "ds": "2026-05-03",
        "actual": 63.0,
        "predicted": 21.984217897340084
      },
      {
        "ds": "2026-05-10",
        "actual": 74.0,
        "predicted": 21.411256608071152
      },
      {
        "ds": "2026-05-17",
        "actual": 68.0,
        "predicted": 21.56934496250671
      },
      {
        "ds": "2026-05-24",
        "actual": 46.0,
        "predicted": 22.15040631942894
      },
      {
        "ds": "2026-05-31",
        "actual": 46.0,
        "predicted": 22.383974643321437
      },
      {
        "ds": "2026-06-07",
        "actual": 55.0,
        "predicted": 22.013825368072002
      },
      {
        "ds": "2026-06-14",
        "actual": 52.0,
        "predicted": 21.531535970978492
      },
      {
        "ds": "2026-06-21",
        "actual": 52.0,
        "predicted": 21.473626830139526
      },
      {
        "ds": "2026-06-28",
        "actual": 30.0,
        "predicted": 21.791085487331056
      },
      {
        "ds": "2026-07-05",
        "actual": 28.0,
        "predicted": 22.096718993055916
      },
      {
        "ds": "2026-07-12",
        "actual": 21.0,
        "predicted": 22.346108924355395
      },
      {
        "ds": "2026-07-19",
        "actual": 22.0,
        "predicted": 22.93090733475607
      },
      {
        "ds": "2026-07-26",
        "actual": 23.0,
        "predicted": 24.018545411572518
      },
      {
        "ds": "2026-08-02",
        "actual": 24.0,
        "predicted": 25.069260780538503
      },
      {
        "ds": "2026-08-09",
        "actual": 39.0,
        "predicted": 25.28298298530538
      }
    ],
    "health": [
      {
        "ds": "2026-02-15",
        "actual": 69.0,
        "predicted": 68.96195078201045
      },
      {
        "ds": "2026-02-22",
        "actual": 73.0,
        "predicted": 68.78277601368984
      },
      {
        "ds": "2026-03-01",
        "actual": 73.0,
        "predicted": 67.6659254596995
      },
      {
        "ds": "2026-03-08",
        "actual": 70.0,
        "predicted": 66.98835881167862
      },
      {
        "ds": "2026-03-15",
        "actual": 67.0,
        "predicted": 67.09541114949691
      },
      {
        "ds": "2026-03-22",
        "actual": 70.0,
        "predicted": 66.84944324395819
      },
      {
        "ds": "2026-03-29",
        "actual": 73.0,
        "predicted": 65.30615359192079
      },
      {
        "ds": "2026-04-05",
        "actual": 75.0,
        "predicted": 63.15357450848935
      },
      {
        "ds": "2026-04-12",
        "actual": 77.0,
        "predicted": 61.97096039759847
      },
      {
        "ds": "2026-04-19",
        "actual": 75.0,
        "predicted": 62.26516064037951
      },
      {
        "ds": "2026-04-26",
        "actual": 77.0,
        "predicted": 62.81391535720163
      },
      {
        "ds": "2026-05-03",
        "actual": 81.0,
        "predicted": 62.145720351715006
      },
      {
        "ds": "2026-05-10",
        "actual": 82.0,
        "predicted": 60.28908750363944
      },
      {
        "ds": "2026-05-17",
        "actual": 80.0,
        "predicted": 58.66193811044348
      },
      {
        "ds": "2026-05-24",
        "actual": 71.0,
        "predicted": 58.35905501597051
      },
      {
        "ds": "2026-05-31",
        "actual": 69.0,
        "predicted": 59.01498384594274
      },
      {
        "ds": "2026-06-07",
        "actual": 70.0,
        "predicted": 59.517119828625596
      },
      {
        "ds": "2026-06-14",
        "actual": 73.0,
        "predicted": 59.451389852534746
      },
      {
        "ds": "2026-06-21",
        "actual": 83.0,
        "predicted": 59.398311044744304
      },
      {
        "ds": "2026-06-28",
        "actual": 64.0,
        "predicted": 59.88981491458466
      },
      {
        "ds": "2026-07-05",
        "actual": 72.0,
        "predicted": 60.605098921228866
      },
      {
        "ds": "2026-07-12",
        "actual": 100.0,
        "predicted": 60.905157652169905
      },
      {
        "ds": "2026-07-19",
        "actual": 80.0,
        "predicted": 60.85958747937255
      },
      {
        "ds": "2026-07-26",
        "actual": 62.0,
        "predicted": 61.22220428620993
      },
      {
        "ds": "2026-08-02",
        "actual": 58.0,
        "predicted": 62.311159324259116
      },
      {
        "ds": "2026-08-09",
        "actual": 58.0,
        "predicted": 63.35974994997075
      }
    ],
    "garden": [
      {
        "ds": "2026-02-15",
        "actual": 20.0,
        "predicted": 15.517575111199646
      },
      {
        "ds": "2026-02-22",
        "actual": 22.0,
        "predicted": 19.469848570688185
      },
      {
        "ds": "2026-03-01",
        "actual": 27.0,
        "predicted": 24.37957699730499
      },
      {
        "ds": "2026-03-08",
        "actual": 38.0,
        "predicted": 29.09723934676625
      },
      {
        "ds": "2026-03-15",
        "actual": 41.0,
        "predicted": 33.38928332566717
      },
      {
        "ds": "2026-03-22",
        "actual": 55.0,
        "predicted": 38.37669816037321
      },
      {
        "ds": "2026-03-29",
        "actual": 75.0,
        "predicted": 45.27455119966773
      },
      {
        "ds": "2026-04-05",
        "actual": 93.0,
        "predicted": 53.76722750122803
      },
      {
        "ds": "2026-04-12",
        "actual": 100.0,
        "predicted": 61.924705034916485
      },
      {
        "ds": "2026-04-19",
        "actual": 93.0,
        "predicted": 67.83686571348115
      },
      {
        "ds": "2026-04-26",
        "actual": 78.0,
        "predicted": 71.14099006498947
      },
      {
        "ds": "2026-05-03",
        "actual": 73.0,
        "predicted": 72.76740014976163
      },
      {
        "ds": "2026-05-10",
        "actual": 81.0,
        "predicted": 73.36458724163774
      },
      {
        "ds": "2026-05-17",
        "actual": 90.0,
        "predicted": 72.40391798518506
      },
      {
        "ds": "2026-05-24",
        "actual": 83.0,
        "predicted": 69.05678115479617
      },
      {
        "ds": "2026-05-31",
        "actual": 86.0,
        "predicted": 63.722309209435274
      },
      {
        "ds": "2026-06-07",
        "actual": 80.0,
        "predicted": 58.26635327119459
      },
      {
        "ds": "2026-06-14",
        "actual": 81.0,
        "predicted": 54.57191747466164
      },
      {
        "ds": "2026-06-21",
        "actual": 78.0,
        "predicted": 52.99423211525317
      },
      {
        "ds": "2026-06-28",
        "actual": 61.0,
        "predicted": 52.380317976432096
      },
      {
        "ds": "2026-07-05",
        "actual": 55.0,
        "predicted": 51.47336052117936
      },
      {
        "ds": "2026-07-12",
        "actual": 51.0,
        "predicted": 50.046223335105125
      },
      {
        "ds": "2026-07-19",
        "actual": 52.0,
        "predicted": 48.663058944468006
      },
      {
        "ds": "2026-07-26",
        "actual": 51.0,
        "predicted": 47.67691334771628
      },
      {
        "ds": "2026-08-02",
        "actual": 50.0,
        "predicted": 46.79135932347092
      },
      {
        "ds": "2026-08-09",
        "actual": 53.0,
        "predicted": 45.54524449551597
      }
    ],
    "toys": [
      {
        "ds": "2026-02-15",
        "actual": 51.0,
        "predicted": 41.27579020823921
      },
      {
        "ds": "2026-02-22",
        "actual": 48.0,
        "predicted": 41.987174312363535
      },
      {
        "ds": "2026-03-01",
        "actual": 46.0,
        "predicted": 42.32628323181111
      },
      {
        "ds": "2026-03-08",
        "actual": 48.0,
        "predicted": 42.05118733252143
      },
      {
        "ds": "2026-03-15",
        "actual": 49.0,
        "predicted": 41.929581235491824
      },
      {
        "ds": "2026-03-22",
        "actual": 52.0,
        "predicted": 42.55297245332778
      },
      {
        "ds": "2026-03-29",
        "actual": 63.0,
        "predicted": 43.37407382777883
      },
      {
        "ds": "2026-04-05",
        "actual": 64.0,
        "predicted": 43.28668335001952
      },
      {
        "ds": "2026-04-12",
        "actual": 65.0,
        "predicted": 41.992510333880126
      },
      {
        "ds": "2026-04-19",
        "actual": 56.0,
        "predicted": 40.40644928467362
      },
      {
        "ds": "2026-04-26",
        "actual": 54.0,
        "predicted": 39.63282290486194
      },
      {
        "ds": "2026-05-03",
        "actual": 57.0,
        "predicted": 39.83704708554187
      },
      {
        "ds": "2026-05-10",
        "actual": 62.0,
        "predicted": 40.350079883099184
      },
      {
        "ds": "2026-05-17",
        "actual": 55.0,
        "predicted": 40.69421964615721
      },
      {
        "ds": "2026-05-24",
        "actual": 49.0,
        "predicted": 41.12260121754664
      },
      {
        "ds": "2026-05-31",
        "actual": 50.0,
        "predicted": 42.06581698903602
      },
      {
        "ds": "2026-06-07",
        "actual": 54.0,
        "predicted": 43.382052193396824
      },
      {
        "ds": "2026-06-14",
        "actual": 51.0,
        "predicted": 44.486881365976984
      },
      {
        "ds": "2026-06-21",
        "actual": 55.0,
        "predicted": 45.143419798778865
      },
      {
        "ds": "2026-06-28",
        "actual": 47.0,
        "predicted": 45.75653821846233
      },
      {
        "ds": "2026-07-05",
        "actual": 49.0,
        "predicted": 46.72263163888926
      },
      {
        "ds": "2026-07-12",
        "actual": 47.0,
        "predicted": 47.743063752345385
      },
      {
        "ds": "2026-07-19",
        "actual": 48.0,
        "predicted": 48.11415120413228
      },
      {
        "ds": "2026-07-26",
        "actual": 47.0,
        "predicted": 47.66575388832735
      },
      {
        "ds": "2026-08-02",
        "actual": 45.0,
        "predicted": 47.05622742906873
      },
      {
        "ds": "2026-08-09",
        "actual": 44.0,
        "predicted": 46.929650348236464
      }
    ]
  },
  "census_recent": [
    {
      "period": "2023-01-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 18427
    },
    {
      "period": "2023-02-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 19902
    },
    {
      "period": "2023-03-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 23641
    },
    {
      "period": "2023-04-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 23422
    },
    {
      "period": "2023-05-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 25160
    },
    {
      "period": "2023-06-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 23528
    },
    {
      "period": "2023-07-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 24075
    },
    {
      "period": "2023-08-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 25772
    },
    {
      "period": "2023-09-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 22573
    },
    {
      "period": "2023-10-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 23143
    },
    {
      "period": "2023-11-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 27490
    },
    {
      "period": "2023-12-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 39318
    },
    {
      "period": "2024-01-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 18472
    },
    {
      "period": "2024-02-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 21169
    },
    {
      "period": "2024-03-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 24109
    },
    {
      "period": "2024-04-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 23150
    },
    {
      "period": "2024-05-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 26511
    },
    {
      "period": "2024-06-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 24285
    },
    {
      "period": "2024-07-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 24575
    },
    {
      "period": "2024-08-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 26262
    },
    {
      "period": "2024-09-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 22259
    },
    {
      "period": "2024-10-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 24359
    },
    {
      "period": "2024-11-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 28716
    },
    {
      "period": "2024-12-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 39876
    },
    {
      "period": "2025-01-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 19461
    },
    {
      "period": "2025-02-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 20653
    },
    {
      "period": "2025-03-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 24941
    },
    {
      "period": "2025-04-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 24739
    },
    {
      "period": "2025-05-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 27920
    },
    {
      "period": "2025-06-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 24976
    },
    {
      "period": "2025-07-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 26670
    },
    {
      "period": "2025-08-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 28215
    },
    {
      "period": "2025-09-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 23868
    },
    {
      "period": "2025-10-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 26124
    },
    {
      "period": "2025-11-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 30762
    },
    {
      "period": "2025-12-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 41920
    },
    {
      "period": "2026-01-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 20522
    },
    {
      "period": "2026-02-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 22418
    },
    {
      "period": "2026-03-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 26690
    },
    {
      "period": "2026-04-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 25869
    },
    {
      "period": "2026-05-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 29282
    },
    {
      "period": "2026-06-01",
      "category_id": "clothing",
      "category_name": "Clothing & Accessories",
      "sales_millions_nsa": 26291
    },
    {
      "period": "2023-01-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 7396
    },
    {
      "period": "2023-02-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 6732
    },
    {
      "period": "2023-03-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 7368
    },
    {
      "period": "2023-04-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 6569
    },
    {
      "period": "2023-05-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 7145
    },
    {
      "period": "2023-06-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 7222
    },
    {
      "period": "2023-07-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 7072
    },
    {
      "period": "2023-08-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 7541
    },
    {
      "period": "2023-09-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 7393
    },
    {
      "period": "2023-10-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 7301
    },
    {
      "period": "2023-11-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 8625
    },
    {
      "period": "2023-12-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 9826
    },
    {
      "period": "2024-01-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 7267
    },
    {
      "period": "2024-02-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 7132
    },
    {
      "period": "2024-03-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 7075
    },
    {
      "period": "2024-04-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 6847
    },
    {
      "period": "2024-05-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 7504
    },
    {
      "period": "2024-06-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 7147
    },
    {
      "period": "2024-07-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 7490
    },
    {
      "period": "2024-08-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 7512
    },
    {
      "period": "2024-09-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 6883
    },
    {
      "period": "2024-10-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 7224
    },
    {
      "period": "2024-11-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 8772
    },
    {
      "period": "2024-12-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 10330
    },
    {
      "period": "2025-01-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 7050
    },
    {
      "period": "2025-02-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 6630
    },
    {
      "period": "2025-03-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 7199
    },
    {
      "period": "2025-04-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 6820
    },
    {
      "period": "2025-05-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 7437
    },
    {
      "period": "2025-06-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 7147
    },
    {
      "period": "2025-07-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 7647
    },
    {
      "period": "2025-08-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 7626
    },
    {
      "period": "2025-09-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 7413
    },
    {
      "period": "2025-10-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 7493
    },
    {
      "period": "2025-11-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 8894
    },
    {
      "period": "2025-12-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 10689
    },
    {
      "period": "2026-01-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 7362
    },
    {
      "period": "2026-02-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 6975
    },
    {
      "period": "2026-03-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 7682
    },
    {
      "period": "2026-04-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 7429
    },
    {
      "period": "2026-05-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 7896
    },
    {
      "period": "2026-06-01",
      "category_id": "electronics",
      "category_name": "Electronics",
      "sales_millions_nsa": 7769
    },
    {
      "period": "2023-01-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 34795
    },
    {
      "period": "2023-02-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 33711
    },
    {
      "period": "2023-03-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 41509
    },
    {
      "period": "2023-04-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 42867
    },
    {
      "period": "2023-05-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 50120
    },
    {
      "period": "2023-06-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 45974
    },
    {
      "period": "2023-07-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 41538
    },
    {
      "period": "2023-08-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 43636
    },
    {
      "period": "2023-09-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 39666
    },
    {
      "period": "2023-10-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 41722
    },
    {
      "period": "2023-11-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 39514
    },
    {
      "period": "2023-12-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 36403
    },
    {
      "period": "2024-01-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 32594
    },
    {
      "period": "2024-02-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 33608
    },
    {
      "period": "2024-03-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 38450
    },
    {
      "period": "2024-04-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 44528
    },
    {
      "period": "2024-05-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 48136
    },
    {
      "period": "2024-06-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 43334
    },
    {
      "period": "2024-07-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 43769
    },
    {
      "period": "2024-08-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 42578
    },
    {
      "period": "2024-09-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 40035
    },
    {
      "period": "2024-10-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 44693
    },
    {
      "period": "2024-11-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 39856
    },
    {
      "period": "2024-12-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 36876
    },
    {
      "period": "2025-01-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 32904
    },
    {
      "period": "2025-02-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 31549
    },
    {
      "period": "2025-03-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 39789
    },
    {
      "period": "2025-04-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 45042
    },
    {
      "period": "2025-05-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 46780
    },
    {
      "period": "2025-06-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 43863
    },
    {
      "period": "2025-07-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 43162
    },
    {
      "period": "2025-08-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 40324
    },
    {
      "period": "2025-09-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 40232
    },
    {
      "period": "2025-10-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 42289
    },
    {
      "period": "2025-11-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 37873
    },
    {
      "period": "2025-12-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 38130
    },
    {
      "period": "2026-01-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 33736
    },
    {
      "period": "2026-02-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 32663
    },
    {
      "period": "2026-03-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 42057
    },
    {
      "period": "2026-04-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 46563
    },
    {
      "period": "2026-05-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 47565
    },
    {
      "period": "2026-06-01",
      "category_id": "garden",
      "category_name": "Patio, Lawn & Garden",
      "sales_millions_nsa": 47822
    },
    {
      "period": "2023-01-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 34119
    },
    {
      "period": "2023-02-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 32229
    },
    {
      "period": "2023-03-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 36087
    },
    {
      "period": "2023-04-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 34073
    },
    {
      "period": "2023-05-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 36388
    },
    {
      "period": "2023-06-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 35841
    },
    {
      "period": "2023-07-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 34108
    },
    {
      "period": "2023-08-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 36566
    },
    {
      "period": "2023-09-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 35471
    },
    {
      "period": "2023-10-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 38007
    },
    {
      "period": "2023-11-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 36630
    },
    {
      "period": "2023-12-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 39976
    },
    {
      "period": "2024-01-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 35827
    },
    {
      "period": "2024-02-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 34120
    },
    {
      "period": "2024-03-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 35660
    },
    {
      "period": "2024-04-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 35349
    },
    {
      "period": "2024-05-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 36676
    },
    {
      "period": "2024-06-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 35084
    },
    {
      "period": "2024-07-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 37310
    },
    {
      "period": "2024-08-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 38017
    },
    {
      "period": "2024-09-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 37708
    },
    {
      "period": "2024-10-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 39647
    },
    {
      "period": "2024-11-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 37285
    },
    {
      "period": "2024-12-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 42257
    },
    {
      "period": "2025-01-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 37352
    },
    {
      "period": "2025-02-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 35484
    },
    {
      "period": "2025-03-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 38832
    },
    {
      "period": "2025-04-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 38492
    },
    {
      "period": "2025-05-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 39339
    },
    {
      "period": "2025-06-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 39043
    },
    {
      "period": "2025-07-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 39981
    },
    {
      "period": "2025-08-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 39797
    },
    {
      "period": "2025-09-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 40800
    },
    {
      "period": "2025-10-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 42196
    },
    {
      "period": "2025-11-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 38653
    },
    {
      "period": "2025-12-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 45615
    },
    {
      "period": "2026-01-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 37785
    },
    {
      "period": "2026-02-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 36149
    },
    {
      "period": "2026-03-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 40379
    },
    {
      "period": "2026-04-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 39324
    },
    {
      "period": "2026-05-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 39686
    },
    {
      "period": "2026-06-01",
      "category_id": "health",
      "category_name": "Health & Personal Care",
      "sales_millions_nsa": 40184
    },
    {
      "period": "2023-01-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 11121
    },
    {
      "period": "2023-02-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 10678
    },
    {
      "period": "2023-03-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 12098
    },
    {
      "period": "2023-04-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 10868
    },
    {
      "period": "2023-05-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 11541
    },
    {
      "period": "2023-06-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 11338
    },
    {
      "period": "2023-07-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 10970
    },
    {
      "period": "2023-08-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 11726
    },
    {
      "period": "2023-09-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 11092
    },
    {
      "period": "2023-10-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 10707
    },
    {
      "period": "2023-11-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 11958
    },
    {
      "period": "2023-12-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 11490
    },
    {
      "period": "2024-01-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 9745
    },
    {
      "period": "2024-02-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 10140
    },
    {
      "period": "2024-03-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 10801
    },
    {
      "period": "2024-04-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 10388
    },
    {
      "period": "2024-05-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 11186
    },
    {
      "period": "2024-06-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 10597
    },
    {
      "period": "2024-07-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 11145
    },
    {
      "period": "2024-08-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 11679
    },
    {
      "period": "2024-09-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 11038
    },
    {
      "period": "2024-10-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 11194
    },
    {
      "period": "2024-11-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 12345
    },
    {
      "period": "2024-12-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 12455
    },
    {
      "period": "2025-01-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 10414
    },
    {
      "period": "2025-02-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 10444
    },
    {
      "period": "2025-03-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 11549
    },
    {
      "period": "2025-04-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 11219
    },
    {
      "period": "2025-05-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 11766
    },
    {
      "period": "2025-06-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 11053
    },
    {
      "period": "2025-07-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 11808
    },
    {
      "period": "2025-08-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 11585
    },
    {
      "period": "2025-09-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 10888
    },
    {
      "period": "2025-10-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 11230
    },
    {
      "period": "2025-11-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 11855
    },
    {
      "period": "2025-12-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 11764
    },
    {
      "period": "2026-01-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 10007
    },
    {
      "period": "2026-02-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 9976
    },
    {
      "period": "2026-03-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 11486
    },
    {
      "period": "2026-04-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 10840
    },
    {
      "period": "2026-05-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 11508
    },
    {
      "period": "2026-06-01",
      "category_id": "home_kitchen",
      "category_name": "Home & Kitchen",
      "sales_millions_nsa": 11270
    },
    {
      "period": "2023-01-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 6933
    },
    {
      "period": "2023-02-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 6493
    },
    {
      "period": "2023-03-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 7889
    },
    {
      "period": "2023-04-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 7622
    },
    {
      "period": "2023-05-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 7980
    },
    {
      "period": "2023-06-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 8274
    },
    {
      "period": "2023-07-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 8159
    },
    {
      "period": "2023-08-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 8853
    },
    {
      "period": "2023-09-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 7892
    },
    {
      "period": "2023-10-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 7620
    },
    {
      "period": "2023-11-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 9047
    },
    {
      "period": "2023-12-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 11466
    },
    {
      "period": "2024-01-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 6812
    },
    {
      "period": "2024-02-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 6627
    },
    {
      "period": "2024-03-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 7691
    },
    {
      "period": "2024-04-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 7056
    },
    {
      "period": "2024-05-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 7718
    },
    {
      "period": "2024-06-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 7846
    },
    {
      "period": "2024-07-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 7695
    },
    {
      "period": "2024-08-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 8550
    },
    {
      "period": "2024-09-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 7455
    },
    {
      "period": "2024-10-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 7552
    },
    {
      "period": "2024-11-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 8959
    },
    {
      "period": "2024-12-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 11543
    },
    {
      "period": "2025-01-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 6683
    },
    {
      "period": "2025-02-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 6205
    },
    {
      "period": "2025-03-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 7721
    },
    {
      "period": "2025-04-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 7154
    },
    {
      "period": "2025-05-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 7869
    },
    {
      "period": "2025-06-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 7749
    },
    {
      "period": "2025-07-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 8024
    },
    {
      "period": "2025-08-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 8927
    },
    {
      "period": "2025-09-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 7681
    },
    {
      "period": "2025-10-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 7960
    },
    {
      "period": "2025-11-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 9342
    },
    {
      "period": "2025-12-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 12293
    },
    {
      "period": "2026-01-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 7160
    },
    {
      "period": "2026-02-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 6838
    },
    {
      "period": "2026-03-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 8269
    },
    {
      "period": "2026-04-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 7952
    },
    {
      "period": "2026-05-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 8764
    },
    {
      "period": "2026-06-01",
      "category_id": "toys",
      "category_name": "Toys & Games",
      "sales_millions_nsa": 8877
    }
  ],
  "dq_highlights": [
    {
      "id": "DQ-001",
      "title": "Rejected India / INR Kaggle catalog",
      "detail": "The popular \"Amazon Sales Dataset\" is Amazon.in / INR, not a U.S. sales time series. Rejected so U.S. Google Trends and Census would not mix geographies.",
      "severity": "reject"
    },
    {
      "id": "DQ-018",
      "title": "reviews = 0 on 79.3% of catalog rows",
      "detail": "On 1,426,337 products in SRC-KAGGLE-002, reviews is zero on 79.3% of rows. Stars often still populate. Column kept, labeled unreliable \u2014 not treated as review count.",
      "severity": "flag"
    },
    {
      "id": "DQ-022",
      "title": "Sennheiser HD 600 price drift",
      "detail": "ASIN B00004SY4H: Sep 2023 snapshot $299.95 vs live Amazon.com $268.90 on 2026-08-17 (\u221210.4%). Snapshot kept; live check is existence/drift only.",
      "severity": "flag"
    },
    {
      "id": "DQ-023",
      "title": "Galison identifier redirect",
      "detail": "Snapshot 0735372888 (Flower Market puzzle) redirects on live Amazon.com to 0735388059 (Blooming Meadow \u2014 different product). Snapshot row kept as-is.",
      "severity": "flag"
    },
    {
      "id": "DQ-025",
      "title": "26.4\u00d7 catalog imbalance (garden vs clothing)",
      "detail": "Mapped garden catalog: 5,345 products vs clothing 141,291. Equal 500-row samples hide parity. Dashboard shows raw mapped counts.",
      "severity": "flag"
    }
  ]
};
