table FactCensusRetail
	lineageTag: fact-census

	column period
		dataType: dateTime
		formatString: Short Date
		lineageTag: fcr-period
		sourceColumn: period

	column category_id
		dataType: string
		lineageTag: fcr-cat-id
		sourceColumn: category_id

	column sales_millions_nsa
		dataType: double
		formatString: #,0
		lineageTag: fcr-sales
		sourceColumn: sales_millions_nsa

	column preliminary_flag
		dataType: boolean
		lineageTag: fcr-prelim
		sourceColumn: preliminary_flag

	partition FactCensusRetail = m
		mode: import
		source =
		let
			Source = Csv.Document(
				File.Contents("../../../data/processed/fact_census_retail_nsa.csv"),
				[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
			),
			#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {
				{"period", type datetime},
				{"category_id", type text},
				{"sales_millions_nsa", type number},
				{"preliminary_flag", type logical}
			}),
			#"Filtered Rows" = Table.SelectRows(#"Changed Type", each [sales_millions_nsa] <> null and [period] >= #datetime(2021, 1, 1, 0, 0, 0))
		in
			#"Filtered Rows"

	annotation PBI_ResultType = Table
