table FactSearchInterest
	lineageTag: fact-search-interest

	column week_start
		dataType: dateTime
		formatString: Short Date
		lineageTag: fsi-week
		sourceColumn: week_start

	column category_id
		dataType: string
		lineageTag: fsi-cat-id
		sourceColumn: category_id

	column interest
		dataType: int64
		formatString: 0
		lineageTag: fsi-interest
		sourceColumn: interest

	column is_partial
		dataType: boolean
		lineageTag: fsi-partial
		sourceColumn: is_partial

	partition FactSearchInterest = m
		mode: import
		source = 
		let
			Source = Csv.Document(
				File.Contents("../../../data/processed/fact_search_interest.csv"),
				[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
			),
			#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"week_start", type datetime}, {"category_id", type text}, {"category_name", type text}, {"keyword", type text}, {"geo", type text}, {"timeframe", type text}, {"interest", Int64.Type}, {"is_partial", type logical}, {"source_id", type text}, {"source_file", type text}})
		in
			#"Changed Type"

	annotation PBI_ResultType = Table
