table FactForecastMetrics
	lineageTag: fact-forecast-metrics

	column category_id
		dataType: string
		lineageTag: ffm-cat-id
		sourceColumn: category_id

	column mape_pct
		dataType: double
		formatString: 0.0
		lineageTag: ffm-mape
		sourceColumn: mape_pct

	column weak_accuracy_flag
		dataType: boolean
		lineageTag: ffm-weak
		sourceColumn: weak_accuracy_flag

	partition FactForecastMetrics = m
		mode: import
		source = 
		let
			Source = Csv.Document(
				File.Contents("../../../data/processed/fact_forecast_metrics.csv"),
				[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
			),
			#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"category_id", type text}, {"category_name", type text}, {"keyword", type text}, {"model", type text}, {"train_weeks", Int64.Type}, {"test_weeks", Int64.Type}, {"test_start", type text}, {"test_end", type text}, {"mape_pct", type number}, {"weak_accuracy_flag", type logical}, {"weak_accuracy_reason", type text}, {"source_id", type text}})
		in
			#"Changed Type"

	annotation PBI_ResultType = Table
