table FactRollingForecastError
	lineageTag: fact-rolling-error

	column ds
		dataType: dateTime
		formatString: Short Date
		lineageTag: fre-ds
		sourceColumn: ds

	column category_id
		dataType: string
		lineageTag: fre-cat-id
		sourceColumn: category_id

	column actual
		dataType: double
		formatString: 0.0
		lineageTag: fre-actual
		sourceColumn: actual

	column predicted
		dataType: double
		formatString: 0.0
		lineageTag: fre-predicted
		sourceColumn: predicted

	column rolling_mape_4w
		dataType: double
		formatString: 0.0
		lineageTag: fre-rolling-mape
		sourceColumn: rolling_mape_4w

	column uncertainty_tier
		dataType: string
		lineageTag: fre-tier
		sourceColumn: uncertainty_tier

	partition FactRollingForecastError = m
		mode: import
		source = 
		let
			Source = Csv.Document(
				File.Contents("../../../data/processed/fact_rolling_forecast_error.csv"),
				[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
			),
			#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"ds", type datetime}, {"category_id", type text}, {"category_name", type text}, {"keyword", type text}, {"actual", type number}, {"predicted", type number}, {"forecast_error", type number}, {"forecast_error_abs", type number}, {"forecast_error_pct", type number}, {"rolling_mape_4w", type number}, {"uncertainty_tier", type text}, {"source_id", type text}, {"model", type text}})
		in
			#"Changed Type"

	annotation PBI_ResultType = Table
